spring:
  profiles:
    active: dev
  application:
    name: mini-12306
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url:  ${MYSQL_URL}/mini12306
    hikari:
      max-lifetime: 600000          # 10分钟（建议值）
      connection-timeout: 30000     # 连接超时30秒
      idle-timeout: 300000          # 空闲超时5分钟
      maximum-pool-size: 10         # 最大连接数
      minimum-idle: 2               # 最小空闲连接数
      validation-timeout: 5000      # 验证超时5秒
      leak-detection-threshold: 60000  # 连接泄漏检测阈值1分钟
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      base-url: https://api.bianxie.ai
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        base-url: https://api.bianxie.ai
        api-key: ${spring.ai.openai.embedding.api-key}
        options:
          model: text-embedding-3-small

app:
  upload:
    path: ${user.home}/mini12306/uploads
    max-file-size: 5MB
    allowed-types: jpg,jpeg,png,gif
