spring:
  profiles:
    active: dev
  application:
    name: mini-12306
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url:  ${MYSQL_URL}/mini12306

app:
  upload:
    path: ${user.home}/mini12306/uploads
    max-file-size: 5MB
    allowed-types: jpg,jpeg,png,gif
