spring:
  profiles:
    active: dev
  application:
    name: mini-12306
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url:  ${MYSQL_URL}/mini12306
    hikari:
      max-lifetime: 1800000
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      base-url: https://api.bianxie.ai
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        base-url: https://api.bianxie.ai
        api-key: ${spring.ai.openai.embedding.api-key}
        options:
          model: text-embedding-3-small

app:
  upload:
    path: ${user.home}/mini12306/uploads
    max-file-size: 5MB
    allowed-types: jpg,jpeg,png,gif
